### ISSUE TITLE
yarn build throws errors on mac os 10.15.4

### ISSUE THREAD

**Issue by selfagency** [erikdubbelboer/node-sleep#105]
I get this any time I run `yarn global` after globally installing a package that uses `sleep` as a dependency. I'm using Yarn 1.22.4 and Node 12.16.2 on Mac OS 10.15.4.

```
warning Error running install script for optional dependency: "/Users/daniel/.config/yarn/global/node_modules/sleep: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/daniel/.config/yarn/global/node_modules/sleep
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.16.2 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/daniel/.config/nvm/12.16.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/daniel/.config/yarn/global/node_modules/sleep/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/daniel/.config/nvm/12.16.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/daniel/Library/Caches/node-gyp/12.16.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/daniel/Library/Caches/node-gyp/12.16.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/daniel/.config/nvm/12.16.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/daniel/Library/Caches/node-gyp/12.16.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/daniel/.config/yarn/global/node_modules/sleep',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/node_sleep/sleep.o
../sleep.cc:6:11: error: no member named 'Handle' in namespace 'v8'
using v8::Handle;
      ~~~~^
../sleep.cc:42:30: error: too few arguments to function call, single argument 'context' was not specified
  sleep(info[0]->Uint32Value());
        ~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2707:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/daniel/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../sleep.cc:54:31: error: too few arguments to function call, single argument 'context' was not specified
  usleep(info[0]->Uint32Value());
         ~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2707:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/daniel/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../sleep.cc:62:52: error: too few arguments to function call, single argument 'context' was not specified
    Nan::New<FunctionTemplate>(Sleep)->GetFunction());
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/12.16.2/include/node/v8.h:6126:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/daniel/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../sleep.cc:64:53: error: too few arguments to function call, single argument 'context' was not specified
    Nan::New<FunctionTemplate>(USleep)->GetFunction());
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/daniel/Library/Caches/node-gyp/12.16.2/include/node/v8.h:6126:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/daniel/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
5 errors generated.
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/daniel/.config/nvm/12.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command \"/Users/daniel/.config/nvm/12.16.2/bin/node\" \"/Users/daniel/.config/nvm/12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/daniel/.config/yarn/global/node_modules/sleep
```

**Comment by erikdubbelboer** [comment]
Seems like you're installing a very old version of `sleep` that is not compatible with node 12. Please install the latest version.
