### ISSUE TITLE
npm install sleep error

### ISSUE THREAD

**Issue by bitsofinfo** [ErikDubbelboer/node-sleep#23]
Building on windows server 2012, getting this error

C:\Users\me\nodejs\myapp\node_modules\sleep>node "C:\Users\me\AppData\Roaming\nvm\v0.10.35\node_modules\npm\bin\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild sleep
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".

**Comment by ErikDubbelboer** [comment]
Can you please try again with the new version?

**Comment by bitsofinfo** [comment]
Different error now

```
PS C:\Users\Administrator\junk> npm version
{ http_parser: '1.0',
  node: '0.10.35',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.30',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1j',
  npm: '1.4.28' }


PS C:\Users\Administrator\junk> npm install sleep

> sleep@2.0.0 install C:\Users\Administrator\junk\node_modules\sleep
> node-gyp rebuild


C:\Users\Administrator\junk\node_modules\sleep>node "C:\Users\Administrator\AppData\Roaming\nvm\v0.10.35\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  sleep.cc
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h': No such file or directory [C:\Users\A
dministrator\junk\node_modules\sleep\build\node_sleep.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\nvm\v0.10.35\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\Administrator\\AppData\\Roaming\\nvm\\v0.10.35\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\junk\node_modules\sleep
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! sleep@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@2.0.0 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep"
npm ERR! cwd C:\Users\Administrator\junk
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by ErikDubbelboer** [comment]
```
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h': No such file or directory [C:\Users\A
dministrator\junk\node_modules\sleep\build\node_sleep.vcxproj]
```

Looks like you are missing some header files. Please check issue #18 where someone had the same problem.
