### ISSUE TITLE
npm install fail 

### ISSUE THREAD

**Issue by lorenzomassacci** [ErikDubbelboer/node-sleep#27]
when I exec npm install I obtain this error:
```
npm http GET https://registry.npmjs.org/sleep/2.0.0
npm http 304 https://registry.npmjs.org/sleep/2.0.0

> sleep@2.0.0 install /Users/lorenzo/Documents/ProgettiWeb/scripts/node_modules/sleep
> node-gyp rebuild

  CXX(target) Release/obj.target/node_sleep/sleep.o
In file included from ../sleep.cc:2:
../../nan/nan.h:23:10: fatal error: 'uv.h' file not found
#include <uv.h>
         ^
1 error generated.
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lorenzo/Documents/ProgettiWeb/bitq-mobile/scripts/node_modules/sleep
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! sleep@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@2.0.0 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/lorenzo/Documents/ProgettiWeb/bitq-mobile/scripts
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/lorenzo/Documents/ProgettiWeb/bitq-mobile/scripts/npm-debug.log
npm ERR! not ok code 0
```

Any ideas?

**Comment by ErikDubbelboer** [comment]
This seems to be an issue with how you installed nodejs. How did you install it?

The file should be in `/usr/local/include/node/uv.h`

**Comment by andrewhao** [comment]
Here's my backtrace:

```
2.2.0 in rxlocation/ on master with unpushed
› npm install
\
> sleep@2.0.0 install /Users/andrewhao/personal/rxlocation/node_modules/sleep
> node-gyp rebuild


module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8. while trying to load binding.gyp
```

**Comment by ErikDubbelboer** [comment]
@andrewhao [nan](https://www.npmjs.com/package/nan) is the only required dependency: https://github.com/ErikDubbelboer/node-sleep/blob/master/package.json#L18
I'm not sure why your npm invocation is not installing the dependencies? Can you show some more of your environment and package.json file?

**Comment by mycetophorae** [comment]
![2015-04-28 09_33_13-command prompt](https://cloud.githubusercontent.com/assets/1079144/7360050/aac84e2c-ed89-11e4-9cd9-08a0ade84552.png)

I'm getting the same error in Windows.  I feel like I should note this is the first time I've had this issue with a node package.

**Comment by ErikDubbelboer** [comment]
@mycetophorae In your output it says:

    TypeError: Invalid Version: 3.5.0a2
    ...
    This is a bug in `node-gyp`.
    Try to update node-gyp and file an Issue if it does not help

I'm afraid this has nothing to do with node-sleep.

**Comment by mycetophorae** [comment]
lol :$

**Comment by yeshwanth-reddy** [comment]
Same problem with me @mycetophorae

**Comment by ErikDubbelboer** [comment]
I did some searching and it seems node-gyp only supports python 2.7.*. I'm guessing you guys have python 3.5.*?

**Comment by tryceo** [comment]
same problem here

**Comment by ErikDubbelboer** [comment]
@tryceo which python version are you running?

**Comment by tryceo** [comment]
2.7

**Comment by ErikDubbelboer** [comment]
@tryceo which of the above errors are you getting exactly?

**Comment by tryceo** [comment]
the output looks exactly like @mycetophorae

**Comment by ErikDubbelboer** [comment]
@tryceo In that case I'm afraid it has nothing to do with node-sleep. `node-gyp` says so itself:

    TypeError: Invalid Version: 3.5.0a2
    ...
    This is a bug in `node-gyp`.
    Try to update node-gyp and file an Issue if it does not help

Please file an issue with them: https://github.com/npm/npm/issues
