### ISSUE TITLE
npm install starts to fail

### ISSUE THREAD

**Issue by chenchaoyi** [ErikDubbelboer/node-sleep#32]
This just happened all of a sudden on Jul 31, 2015, I didn't see any change in node-sleep itself, nor there was any changes in the env. No idea how this happens:
```
$ npm install sleep
\
> sleep@2.0.0 install /private/tmp/node_modules/sleep
> node-gyp rebuild

  CXX(target) Release/obj.target/node_sleep/sleep.o
../sleep.cc:36:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../sleep.cc:38:7: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1 || !args[0]->IsUint32()) {
      ^~~~
      uv_process_options_s::args
/Users/cchen21/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:38:7: error: invalid use of non-static data member 'args'
  if (args.Length() < 1 || !args[0]->IsUint32()) {
      ^~~~
../sleep.cc:38:29: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1 || !args[0]->IsUint32()) {
                            ^~~~
                            uv_process_options_s::args
/Users/cchen21/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:38:29: error: invalid use of non-static data member 'args'
  if (args.Length() < 1 || !args[0]->IsUint32()) {
                            ^~~~
../sleep.cc:39:12: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
    return NanThrowError("Expected number of seconds");
           ^~~~~~~~~~~~~
           Nan::ThrowError
../node_modules/nan/nan.h:631:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../node_modules/nan/nan.h:619:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:94:1: note: expanded from here
ThrowError
^
../sleep.cc:42:9: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  sleep(args[0]->Uint32Value());
        ^~~~
        uv_process_options_s::args
/Users/cchen21/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:42:9: error: invalid use of non-static data member 'args'
  sleep(args[0]->Uint32Value());
        ^~~~
../sleep.cc:44:3: error: use of undeclared identifier 'NanReturnUndefined'
  NanReturnUndefined();
  ^
../sleep.cc:48:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../sleep.cc:50:7: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1 || !args[0]->IsUint32()) {
      ^~~~
      uv_process_options_s::args
/Users/cchen21/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:50:7: error: invalid use of non-static data member 'args'
  if (args.Length() < 1 || !args[0]->IsUint32()) {
      ^~~~
../sleep.cc:50:29: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1 || !args[0]->IsUint32()) {
                            ^~~~
                            uv_process_options_s::args
/Users/cchen21/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:50:29: error: invalid use of non-static data member 'args'
  if (args.Length() < 1 || !args[0]->IsUint32()) {
                            ^~~~
../sleep.cc:51:12: error: use of undeclared identifier 'NanThrowError'; did you mean 'Nan::ThrowError'?
    return NanThrowError("Expected number of microseconds");
           ^~~~~~~~~~~~~
           Nan::ThrowError
../node_modules/nan/nan.h:631:3: note: 'Nan::ThrowError' declared here
  X(Error)
  ^
../node_modules/nan/nan.h:619:21: note: expanded from macro 'X'
    NAN_INLINE void Throw ## NAME(const char *msg) {                           \
                    ^
<scratch space>:94:1: note: expanded from here
ThrowError
^
../sleep.cc:54:10: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  usleep(args[0]->Uint32Value());
         ^~~~
         uv_process_options_s::args
/Users/cchen21/.node-gyp/0.12.7/deps/uv/include/uv.h:857:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../sleep.cc:54:10: error: invalid use of non-static data member 'args'
  usleep(args[0]->Uint32Value());
         ^~~~
../sleep.cc:56:3: error: use of undeclared identifier 'NanReturnUndefined'
  NanReturnUndefined();
  ^
../sleep.cc:61:16: error: use of undeclared identifier 'NanNew'
  exports->Set(NanNew<String>("sleep"), NanNew<FunctionTemplate>(Sleep)->GetFunction());
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/node_modules/sleep
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "sleep"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sleep@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

My npm setting:
```
$ npm version
{ npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```

Mac OS 10.9.5

**Comment by ErikDubbelboer** [comment]
NAN was updated. Should be fixed now in the latest version.

**Comment by fitch** [comment]
I'm still getting this error with `npm install sleep`.
