### ISSUE TITLE
node-gyb build error

### ISSUE THREAD

**Issue by mhingston** [ErikDubbelboer/node-sleep#37]
I can't get sleep 2.0.0 to build for me on Linux, using iojs v3.0.0, npm v2.13.3

	11722 info sleep@2.0.0 Failed to exec install script
	11723 verbose unlock done using /root/.npm/_locks/sleep-4f0ddb4b7a9c428a.lock for /usr/local/lib/mdf/node_modules/sleep
	11724 verbose stack Error: sleep@2.0.0 install: `node-gyp rebuild`
	11724 verbose stack Exit status 1
	11724 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
	11724 verbose stack     at emitTwo (events.js:87:13)
	11724 verbose stack     at EventEmitter.emit (events.js:172:7)
	11724 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
	11724 verbose stack     at emitTwo (events.js:87:13)
	11724 verbose stack     at ChildProcess.emit (events.js:172:7)
	11724 verbose stack     at maybeClose (internal/child_process.js:764:16)
	11724 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
	11725 verbose pkgid sleep@2.0.0
	11726 verbose cwd /usr/local/lib/mdf
	11727 error Linux 3.13.0-61-generic
	11728 error argv "/usr/bin/iojs" "/usr/bin/npm" "install" "--production" "--unsafe-perm"
	11729 error node v3.0.0
	11730 error npm  v2.13.3
	11731 error code ELIFECYCLE
	11732 error sleep@2.0.0 install: `node-gyp rebuild`
	11732 error Exit status 1
	11733 error Failed at the sleep@2.0.0 install script 'node-gyp rebuild'.
	11733 error This is most likely a problem with the sleep package,
	11733 error not with npm itself.
	11733 error Tell the author that this fails on your system:
	11733 error     node-gyp rebuild
	11733 error You can get their info via:
	11733 error     npm owner ls sleep
	11733 error There is likely additional logging output above.
	11734 verbose exit [ 1, true ]
	11735 verbose unbuild node_modules/sleep
	11736 info preuninstall sleep@2.0.0
	11737 info uninstall sleep@2.0.0
	11738 verbose unbuild rmStuff sleep@2.0.0 from /usr/local/lib/mdf/node_modules
	11739 info postuninstall sleep@2.0.0
	11740 silly gentlyRm /usr/local/lib/mdf/node_modules/sleep is being purged from base /usr/local/lib/mdf
	11741 verbose gentlyRm don't care about contents; nuking /usr/local/lib/mdf/node_modules/sleep
	11742 silly vacuum-fs purging /usr/local/lib/mdf/node_modules/sleep
	11743 silly vacuum-fs quitting because other entries in /usr/local/lib/mdf/node_modules

**Comment by mhingston** [comment]
Nevermind, it was my setup.
