### ISSUE TITLE
npm install error on osx 10.10

### ISSUE THREAD

**Issue by daimagine** [ErikDubbelboer/node-sleep#41]
Hi, I found a trouble when trying to install `node-sleep` on my osx 10.10.5 with xcode6 installed. Could you help me point out what went wrong?
This is the logs:
```
Adis-MBP:api adikurniawan$ npm install sleep
npm WARN package.json mailinator-api@0.0.1 No repository field.
\
> sleep@3.0.0 install /Users/adikurniawan/Developer/project/tunity/git/api/node_modules/sleep
> node-gyp rebuild

  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/node_sleep.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node_sleep.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/adikurniawan/.nvm/v0.10.33/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/adikurniawan/.nvm/v0.10.33/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adikurniawan/Developer/project/tunity/git/api/node_modules/sleep
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! sleep@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@3.0.0 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/adikurniawan/.nvm/v0.10.33/bin/node" "/Users/adikurniawan/.nvm/v0.10.33/bin/npm" "install" "sleep"
npm ERR! cwd /Users/adikurniawan/Developer/project/tunity/git/api
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by ErikDubbelboer** [comment]
Are you sure you still have xcode 6? It looks like this: https://github.com/nodejs/node/issues/2933

**Comment by daimagine** [comment]
Yes I am absolutely sure that I had xcode 6 back then. 
After 2 hourish updating to xcode 7 and open it at least once solved my problem. 
Anyway, big thanks for pointing that link. It turned out updating only Command Line Tools without xcode 7 will cause this problem.
