### ISSUE TITLE
required package missing `block-stream`

### ISSUE THREAD

**Issue by panshul007** [erikdubbelboer/node-sleep#57]
while installing I get an error about missing module: `block-stream`

error does not resolve by installing the missing module locally. 
but it does resolve by installing the missing module globally.

Either it should be packed in or specified as a peer dependency.

error: 
```bash
> sleep@4.0.0 install /Users/project/node_modules/sleep
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'block-stream'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:455:15)
gyp ERR! stack     at Function.Module._load (module.js:403:25)
gyp ERR! stack     at Module.require (module.js:483:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar/lib/entry-writer.js:7:19)
gyp ERR! stack     at Module._compile (module.js:556:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:565:10)
gyp ERR! stack     at Module.load (module.js:473:32)
gyp ERR! stack     at tryModuleLoad (module.js:432:12)
gyp ERR! stack     at Function.Module._load (module.js:424:3)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/project/node_modules/sleep
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
```

using the latest Node v6 and npm v3

**Comment by erikdubbelboer** [comment]
If you would actually read the message you would see it has nothing to do with this module:
```
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
```

**Comment by panshul007** [comment]
oh oh... my bad 👍
