### ISSUE TITLE
error installing on windows

### ISSUE THREAD

**Issue by ab690257072** [erikdubbelboer/node-sleep#69]
```
$ npm i -D --verbose sleep
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   '-D',
npm verb cli   '--verbose',
npm verb cli   'sleep' ]
npm info using npm@3.10.10
npm info using node@v6.10.0
npm verb request uri https://registry.npm.taobao.org/sleep
npm verb request no auth needed
npm info attempt registry request try #1 at 21:08:06
npm verb request id 4a4e50af90aaeaa6
npm verb etag "59c6-HXHt/0nenjSkzWmakHWbbg"
npm http request GET https://registry.npm.taobao.org/sleep
npm http 304 https://registry.npm.taobao.org/sleep
npm verb headers { date: 'Tue, 14 Mar 2017 13:08:15 GMT',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-current-requests': '1',
npm verb headers   etag: '"59c6-HXHt/0nenjSkzWmakHWbbg"',
npm verb headers   'x-readtime': '20' }
npm verb etag https://registry.npm.taobao.org/sleep from cache
npm verb get saving sleep to C:\Users\zhao\AppData\Roaming\npm-cache\registry.npm.taobao.org\sleep\.cache.json
npm verb correctMkdir C:\Users\zhao\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb cache add spec sleep@latest
npm verb addNamed "latest" is being treated as a dist-tag for sleep
npm info addNameTag [ 'sleep', 'latest' ]
npm verb addNameTag registry:https://registry.npm.taobao.org/sleep not in flight; fetching
npm verb get https://registry.npm.taobao.org/sleep not expired, no request
npm verb addNamed "5.1.0" is a plain semver version for sleep
npm verb afterAdd C:\Users\zhao\AppData\Roaming\npm-cache\sleep\5.1.0\package\package.json not in flight; writing
npm verb correctMkdir C:\Users\zhao\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb afterAdd C:\Users\zhao\AppData\Roaming\npm-cache\sleep\5.1.0\package\package.json written
npm verb request uri https://registry.npm.taobao.org/fsevents
npm verb request no auth needed
npm info attempt registry request try #1 at 21:08:08
npm verb etag "d3a7-v80PqhWJ8xD4Gaw+KWlP1g"
npm http request GET https://registry.npm.taobao.org/fsevents
npm http 304 https://registry.npm.taobao.org/fsevents
npm verb headers { date: 'Tue, 14 Mar 2017 13:08:17 GMT',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-current-requests': '1',
npm verb headers   etag: '"d3a7-v80PqhWJ8xD4Gaw+KWlP1g"',
npm verb headers   'x-readtime': '18' }
npm verb etag https://registry.npm.taobao.org/fsevents from cache
npm verb get saving fsevents to C:\Users\zhao\AppData\Roaming\npm-cache\registry.npm.taobao.org\fsevents\.cache.json
npm verb correctMkdir C:\Users\zhao\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb correctMkdir C:\Users\zhao\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\zhao\AppData\Roaming\npm-cache\_locks\staging-55a7008df0c462b4.lock for E:\project-managment\node_modules\.staging
npm verb unbuild node_modules\.staging\sleep-dd3ebddc
npm verb gentlyRm don't care about contents; nuking E:\project-managment\node_modules\.staging\sleep-dd3ebddc
npm verb tar unpack C:\Users\zhao\AppData\Roaming\npm-cache\sleep\5.1.0\package.tgz
npm verb tar unpacking to E:\project-managment\node_modules\.staging\sleep-dd3ebddc
npm verb gentlyRm don't care about contents; nuking E:\project-managment\node_modules\.staging\sleep-dd3ebddc
npm verb gentlyRm don't care about contents; nuking E:\project-managment\node_modules\.staging\sleep-dd3ebddc\node_modules
npm info lifecycle sleep@5.1.0~preinstall: sleep@5.1.0
npm info linkStuff sleep@5.1.0
npm verb linkBins sleep@5.1.0
npm verb linkMans sleep@5.1.0
npm info lifecycle sleep@5.1.0~install: sleep@5.1.0

> sleep@5.1.0 install E:\project-managment\node_modules\sleep
> node-gyp rebuild


E:\project-managment\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.10.0 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 C:\Python27\python2.EXE
gyp verb check python version `C:\Python27\python2.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.10.0
gyp verb command install [ '6.10.0' ]
gyp verb install input version string "6.10.0"
gyp verb install installing version: 6.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.10.0
gyp verb build dir attempting to create "build" dir: E:\project-managment\node_modules\sleep\build
gyp verb build dir "build" dir needed to be created? E:\project-managment\node_modules\sleep\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\project-managment\node_modules\sleep\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\project-managment\node_modules\sleep\config.gypi
gyp verb common.gypi checking for gypi file: E:\project-managment\node_modules\sleep\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python2.EXE
gyp info spawn args [ 'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\project-managment\\node_modules\\sleep\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zhao\\.node-gyp\\6.10.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zhao\\.node-gyp\\6.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\project-managment\\node_modules\\sleep',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\project-managment\\node_modules\\sleep\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir C:\Users\zhao\.node-gyp\6.10.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for ia32 C:\Users\zhao\.node-gyp\6.10.0\Release\node.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
▒ڴ˽▒▒▒▒▒▒▒▒һ▒▒▒▒▒▒һ▒▒▒▒Ŀ▒▒▒▒Ҫ▒▒▒ò▒▒▒▒▒▒ɣ▒▒▒▒▒ӡ▒/m▒▒▒▒▒ء▒
▒▒▒▒▒▒▒▒ʱ▒▒Ϊ 2017/3/14 21:08:14▒▒

▒▒▒▒ʧ▒ܡ▒
    0 ▒▒▒▒▒▒
    0 ▒▒▒▒▒▒

▒▒▒▒ʱ▒▒ 00:00:00.06
MSBUILD : error MSB1025: ▒▒▒▒ MSBuild ʱ▒▒▒▒▒ڲ▒▒▒▒▒
Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException: û▒▒Ϊ ToolsVersion▒▒14.0▒▒(▒ڡ▒HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0▒▒▒▒▒▒▒▒)ָ▒▒ MSBuildToolsPath▒▒▒▒▒▒ָ▒▒ֵ▒ļ▒▒▒▒▒Ϊ▒▒▒ַ▒▒▒▒▒
   ▒▒ Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException.Throw(Exception innerException, String resourceName, Object[] args)
   ▒▒ Microsoft.Build.BuildEngine.ToolsetReader.ReadToolset(PropertyDefinition toolsVersion, BuildPropertyGroup globalProperties, BuildPropertyGroup initialProperties, Boolean accumulateProperties)
   ▒▒ Microsoft.Build.BuildEngine.ToolsetReader.ReadEachToolset(ToolsetCollection toolsets, BuildPropertyGroup globalProperties, BuildPropertyGroup initialProperties, Boolean accumulateProperties)
   ▒▒ Microsoft.Build.BuildEngine.ToolsetReader.ReadToolsets(ToolsetCollection toolsets, BuildPropertyGroup globalProperties, BuildPropertyGroup initialProperties, Boolean accumulateProperties)
   ▒▒ Microsoft.Build.BuildEngine.ToolsetReader.ReadAllToolsets(ToolsetCollection toolsets, ToolsetRegistryReader registryReader, ToolsetConfigurationReader configurationReader, BuildPropertyGroup globalProperties, BuildPropertyGroup initialProperties, ToolsetDefinitionLocations locations)
   ▒▒ Microsoft.Build.BuildEngine.Engine.PopulateToolsetStateMap(ToolsetDefinitionLocations locations)
   ▒▒ Microsoft.Build.BuildEngine.Engine..ctor(Int32 numberOfCpus, Boolean isChildNode, Int32 parentNodeId, String localNodeProviderParameters, BuildPropertyGroup globalProperties, ToolsetDefinitionLocations locations)
   ▒▒ Microsoft.Build.BuildEngine.Engine.get_GlobalEngine()
   ▒▒ Microsoft.Build.BuildEngine.Project..ctor(Engine engine, String toolsVersion)
   ▒▒ Microsoft.Build.BuildEngine.SolutionWrapperProject.Generate(String solutionPath, String toolsVersionOverride, BuildEventContext projectBuildEventContext)
   ▒▒ Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapperUsingOldOM(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectRootElementCache projectRootElementCache, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded)
   ▒▒ Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded)
   ▒▒ Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildEventContext buildEventContext)
   ▒▒ Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   ▒▒ Microsoft.Build.Execution.BuildManager.IssueRequestToScheduler(BuildSubmission submission, Boolean allowMainThreadBuild, BuildRequestBlocker blocker)
   ▒▒ Microsoft.Build.Execution.BuildManager.<>c__DisplayClass60_1.<ExecuteSubmission>b__0()

MSBUILD : error MSB1025: ▒▒▒▒ MSBuild ʱ▒▒▒▒▒ڲ▒▒▒▒▒
Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException: û▒▒Ϊ ToolsVersion▒▒14.0▒▒(▒ڡ▒HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0▒▒▒▒▒▒▒▒)ָ▒▒ MSBuildToolsPath▒▒▒▒▒▒ָ▒▒ֵ▒ļ▒▒▒▒▒Ϊ▒▒▒ַ▒▒▒▒▒
   ▒▒ Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
   ▒▒ Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

δ▒▒▒▒▒▒▒▒쳣:  Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException: û▒▒Ϊ ToolsVersion▒▒14.0▒▒(▒ڡ▒HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0▒▒▒▒▒▒▒▒)ָ▒▒ MSBuildToolsPath▒▒▒▒▒▒ָ▒▒ֵ▒ļ▒▒▒▒▒Ϊ▒▒▒ַ▒▒▒▒▒
   ▒▒ Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean debugger, Boolean detailedSummary)
   ▒▒ Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   ▒▒ Microsoft.Build.CommandLine.MSBuildApp.Main()
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 3762504530
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\project-managment\node_modules\sleep
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm verb lifecycle sleep@5.1.0~install: unsafe-perm in lifecycle true
npm verb lifecycle sleep@5.1.0~install: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin;E:\project-managment\node_modules\sleep\node_modules\.bin;E:\project-managment\node_modules\.bin;C:\Users\zhao\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\zhao\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;E:\apache-maven-3.0.5\bin;C:\Program Files\Java\jdk1.7.0_80\bin;C:\Program Files (x86)\nodejs;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Python27;D:\Microsoft VS Code\bin;C:\Users\zhao\AppData\Local\atom\app-1.12.7\resources\app\apm\bin;C:\Python27;C:\Users\zhao\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
npm verb lifecycle sleep@5.1.0~install: CWD: E:\project-managment\node_modules\sleep
npm info lifecycle sleep@5.1.0~install: Failed to exec install script
npm verb unlock done using C:\Users\zhao\AppData\Roaming\npm-cache\_locks\staging-55a7008df0c462b4.lock for E:\project-managment\node_modules\.staging
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: ia32
npm verb stack Error: sleep@5.1.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid sleep@5.1.0
npm verb cwd E:\project-managment
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "--verbose" "sleep"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sleep@5.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@5.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     E:\project-managment\npm-debug.log
```

**Comment by ab690257072** [comment]
What do I need if I want to install sleep on windows platform?
I had installed python2.7, visual studio 2017, windows SDK 10, MSBuild. But it seems to be a hard problem. I can't install sleep.

**Comment by erikdubbelboer** [comment]
Looks like your build environment is not setup properly as I'm seeing https://msdn.microsoft.com/en-us/library/sdbsbb6h.aspx

You might want to look into this guide by Microsoft: https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules

**Comment by ab690257072** [comment]
Thank you very much! I'll have a try.
