### ISSUE TITLE
Cannot install on Alpine

### ISSUE THREAD

**Issue by thalesfsp** [erikdubbelboer/node-sleep#70]
Hi! I'm trying to run a NodeJS project that uses sleep, but I can't:

```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Error loading shared library /x/node_modules/sleep/build/Release/node_sleep.node: Exec format error
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/x/node_modules/sleep/index.js:1:75)
```

I've tried other solutions (google, etc). How can I force to use the fallback?

**Comment by erikdubbelboer** [comment]
How did you install it. Can you give me the output of `npm install --verbose sleep`

**Comment by thalesfsp** [comment]
@erikdubbelboer I don't remember what I did, but I solve that. I will be closing this ticket. Thank you!
