### ISSUE TITLE
Install sleep package failure

### ISSUE THREAD

**Issue by minsooshin** [erikdubbelboer/node-sleep#71]
I am getting this error when I attempted to install `sleep` module.
```sh
npm install --save-dev sleep@^5.1.0

> sleep@5.1.0 install /Users/mshin/Workspace/cre-hero/node_modules/sleep
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 525 response downloading https://nodejs.org/dist/v6.9.1/node-v6.9.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/mshin/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/mshin/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:954:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/mshin/.nvm/versions/node/v6.9.1/bin/node" "/Users/mshin/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mshin/Workspace/cre-hero/node_modules/sleep
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/mshin/.nvm/versions/node/v6.9.1/bin/node" "/Users/mshin/.nvm/versions/node/v6.9.1/bin/npm" "install" "--save-dev" "sleep@^5.1.0"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! sleep@5.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@5.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mshin/Workspace/cre-hero/npm-debug.log
```

I tried with removing `node_modules` directory, but it is same.
Did I miss something that I need to configure?

**Comment by erikdubbelboer** [comment]
It says right there in the log:
```
gyp ERR! stack Error: 525 response downloading https://nodejs.org/dist/v6.9.1/node-v6.9.1-headers.tar.gz
```
No idea why this fails on your system, maybe no internet connection or some firewall?

**Comment by minsooshin** [comment]
@erikdubbelboer thanks!!!
