### ISSUE TITLE
Can't install using latest Node.js

### ISSUE THREAD

**Issue by xeoneux** [erikdubbelboer/node-sleep#75]
I'm using the latest Node.js at v8.1.1 on Ubuntu 16.04
Here's the error that npm throws when installation fails:

```
> sleep@5.1.1 install /home/ubuntu/my-project/node_modules/sleep
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:120:20)
gyp ERR! stack     at Request.emit (events.js:210:7)
gyp ERR! stack     at Request.onRequestResponse (/home/ubuntu/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/request/request.js:1074:10)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! System Linux 4.4.0-1017-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v8.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/ocharge-server/node_modules/sleep
gyp ERR! node -v v8.1.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN mongoosastic@0.2.6 requires a peer of mongoose@3.8.x but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleep@5.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-06-15T10_16_00_629Z-debug.log
```

Is the URL that's used to download headers incorrect in the library itself?

**Comment by erikdubbelboer** [comment]
This seems to be an issue with nodejs itself and has nothing to do with sleep:
```
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
```
Looks like they either forgot to upload these headers or fix gyp to a new locations if they moved them.
