### ISSUE TITLE
Uncaught Error on load

### ISSUE THREAD

**Issue by mMazurkiewicz** [erikdubbelboer/node-sleep#82]
Hi,

i have this error when I start my app:

```
### Uncaught Error: The module '/Users/macos/Documents/workspace/myapp/node_modules/sleep/build/Release/node_sleep.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:713:18)
    at Module.load (module.js:585:32)
    at tryModuleLoad (module.js:528:12)
    at Function.Module._load (module.js:520:3)
    at Module.require (module.js:610:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/macos/Documents/workspace/pauls boutique/Digujto labels/node_modules/sleep/index.js:1:75)
    at Module._compile (module.js:666:30)
    at Object.Module._extensions..js (module.js:683:10)
    at Module.load (module.js:585:32)
```

I am using sleep (installed week ago) with other app and error do not occures.

**Comment by erikdubbelboer** [comment]
Did you update your nodejs after compiling sleep? I guess reinstalling sleep will fix the issue.

**Comment by mMazurkiewicz** [comment]
No, I didn't. 
I've tried to uninstall sleep, then update node, and then install sleep once again and I. still having this error

**Comment by erikdubbelboer** [comment]
If you reinstall sleep and still get this issue it would mean you are installing/compiling sleep with a different version of node than that you run it with later.

**Comment by mMazurkiewicz** [comment]
ok, i've updated node to version 9.0.0 which uses NODE_MODULE_VERSION 59 
[https://nodejs.org/en/download/releases/](https://nodejs.org/en/download/releases/)
and everything works perfectly fine! Thanks!
