### ISSUE TITLE
 Failed at the sleep@5.1.1 install script.

### ISSUE THREAD

**Issue by ManojJV** [erikdubbelboer/node-sleep#88]
When I try to install sleep package it throws me these errors...!
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (C:\Users\mjillell\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\instal
l.js:193:21)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestError (C:\Users\mjillell\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.
js:877:8)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mjillell\\AppData\\Roaming\\npm\\node_modules\\npm\\node_module
s\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mjillell\workspace\project\node_modules\sleep
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleep@5.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@5.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by erikdubbelboer** [comment]
It says:
```
Error: This is most likely not a problem with node-gyp or the package itself and
is related to network connectivity. In most cases you are behind a proxy or have bad
network settings.
```
The stack contains `TLSSocket` and `Request` so I'm guessing its right and you are having some network issues that have nothing do with this package.
