### ISSUE TITLE
Cannot install on OS X

### ISSUE THREAD

**Issue by kittaakos** [erikdubbelboer/node-sleep#92]
The following fails for me on OS X. The propsed solution did not help fixing my [_xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance_](https://github.com/nodejs/node-gyp/issues/569) issue. Does `sleep` work on OS X? Normally, I do not have any issues building native modules on my environment. Let me know if you need more info. Thank you!

```
npm --version && node --version && python --version && rm -rf sleep-test && mkdir sleep-test && cd sleep-test && npm init -y && npm i -S sleep
5.6.0
v8.11.4
Python 2.7.15
Wrote to /Users/akos.kitta/Desktop/sleep-test/package.json:

{
  "name": "sleep-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



> sleep@5.2.3 install /Users/akos.kitta/Desktop/sleep-test/node_modules/sleep
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/akos.kitta/.nvm/versions/node/v8.11.4/bin/node" "/Users/akos.kitta/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/akos.kitta/Desktop/sleep-test/node_modules/sleep
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN sleep-test@1.0.0 No description
npm WARN sleep-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleep@5.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akos.kitta/.npm/_logs/2018-10-23T14_04_42_215Z-debug.log
```

**Comment by kittaakos** [comment]
I have switched back to Python `2.7.10` (with [`pyenv`](https://github.com/pyenv/pyenv)), it did not help.

**Comment by jarrodjperez** [comment]
@kittaakos had the same issue with another node lib. This ended up fixing it for me: https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp

**Comment by kittaakos** [comment]
It worked. Awesome 🎉 Thank you!
