### ISSUE TITLE
npm ERR! Failed at the sleep@5.1.1 install script.

### ISSUE THREAD

**Issue by awesomehimanshu** [erikdubbelboer/node-sleep#94]
I am using node v10.15.0

And in package.json sleep:'^5.1.1'

Can you tell me what is casing issue.

node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  sleep.cc
  win_delay_load_hook.cc
c:\docp_nodejs_project\docp-decoupling-nodejs\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..\sleep.cc) [C:\DOCP_nodejs_project\docp-decoupling-nodejs\node_modules\sleep\build\node_sleep.vcxproj]
  c:\users\h.v.sharma\.node-gyp\10.15.0\include\node\v8.h(3243): note: see declaration of 'v8::Object' (compiling source file ..\sleep.cc)
c:\docp_nodejs_project\docp-decoupling-nodejs\node_modules\nan\nan.h(834): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\sleep.cc) [C:\DOCP_nodejs_project\docp-decoupling-nodejs\node_modules\sleep\build\node_sleep.vcxproj]
  c:\users\h.v.sharma\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling source file ..\sleep.cc)
c:\docp_nodejs_project\docp-decoupling-nodejs\node_modules\nan\nan.h(849): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\sleep.cc) [C:\DOCP_nodejs_project\docp-decoupling-nodejs\node_modules\sleep\build\node_sleep.vcxproj]
  c:\users\h.v.sharma\.node-gyp\10.15.0\include\node\node.h(169): note: see declaration of 'node::MakeCallback' (compiling source file ..\sleep.cc)
c:\docp_nodejs_project\docp-decoupling-nodejs\node_modules\nan\nan.h(864): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\sleep.cc) [C:\DOCP_nodejs_project\docp-decoupling-nodejs\node_modules\sleep\build\node_sleep.vcxproj]
  c:\users\h.v.sharma\.node-gyp\10.15.0\include\node\node.h(162): note: see declaration of 'node::MakeCallback' (compiling source file ..\sleep.cc)
c:\docp_nodejs_project\docp-decoupling-nodejs\node_modules\nan\nan.h(1473): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\sleep.cc) [C:\DOCP_nodejs_project\docp-decoupling-nodejs\node_modules\sleep\build\node_sleep.vcxproj]
  c:\users\h.v.sharma\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling source file ..\sleep.cc)
c:\docp_nodejs_project\docp-decoupling-nodejs\node_modules\sleep\sleep.cc(42): warning C4996: 'v8::Value::Uint32Value': was declared deprecated [C:\DOCP_nodejs_project\docp-decoupling-nodejs\node_modules\sleep\build\node_sleep.vcxproj]
  c:\users\h.v.sharma\.node-gyp\10.15.0\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
c:\docp_nodejs_project\docp-decoupling-nodejs\node_modules\sleep\sleep.cc(54): warning C4996: 'v8::Value::Uint32Value': was declared deprecated [C:\DOCP_nodejs_project\docp-decoupling-nodejs\node_modules\sleep\build\node_sleep.vcxproj]
  c:\users\h.v.sharma\.node-gyp\10.15.0\include\node\v8.h(2477): note: see declaration of 'v8::Value::Uint32Value'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\DOCP_nodejs_project\docp-decoupling-nodejs\node_modules\sleep
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN The package rabbit.js is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@6.0.1 (node_modules\snappy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@6.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleep@5.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@5.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\h.v.sharma\AppData\Roaming\npm-cache\_logs\2019-01-09T07_43_14_859Z-debug.log

**Comment by awesomehimanshu** [comment]
Oh sorry , I downgrade my node version from 10.13 to 8.11 .1 . It was version version . Also it was 3 - 4 month project . I tried other solution also . I remove package-lock.json and then do npm install . it work . because it install respective supported version .
