### ISSUE TITLE
Broken Node 12.1.0

### ISSUE THREAD

**Issue by meabed** [erikdubbelboer/node-sleep#99]
Thank you for maintaining the library.
Its broken when i try to install it after upgrade node version
```
30 warnings and 9 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/meabed/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command \"/usr/local/Cellar/node/12.1.0/bin/node\" \"/Users/meabed/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/meabed/Workspace/validsh/www-api/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/meabed/Workspace/validsh/www-api/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=4\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/meabed/Workspace/validsh/www-api/node_modules/fsevents
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.1.0/bin/node /Users/meabed/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/meabed/Workspace/validsh/www-api/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/meabed/Workspace/validsh/www-api/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/meabed/Workspace/validsh/www-api/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/12.1.0/bin/node\" \"/Users/meabed/Workspace/validsh/www-api/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/meabed/Workspace/validsh/www-api/node_modules/fsevents
node-pre-gyp ERR! node -v v12.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/12.1.0/bin/node /Users/meabed/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/meabed/Workspace/validsh/www-api/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/meabed/Workspace/validsh/www-api/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)"
info This module is OPTIONAL, you can safely ignore this error
```

Thanks

**Comment by erikdubbelboer** [comment]
This has nothing to do with `sleep`. The word `sleep` doesn't event occur in your error message. As the error message says, this has something to do with `fsevents` which is in no way a dependency of `sleep`, so it really has nothing to do with `sleep`.

**Comment by jdalton** [comment]
`nan` doesn't yet support Node 12 so node-sleep will not build successfully. See https://github.com/nodejs/nan/issues/849.

**Comment by erikdubbelboer** [comment]
I have just published a release which is compatible with node 12.
